# amcl_params.yaml --- 
# 
# Filename: amcl_params.yaml
# Description: Configuration for Adaptive Monte Carlo Localization
# Created: Mon Nov 17 23:48:12 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

# Pose prior before localization
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.0625 # 0.25m * 0.25m
initial_cov_yy: 0.0625
initial_cov_aa: 0.5 # apprx (pi/4 rad)*(pi/4 rad) 

# Particle Filter parameters
min_particles: 500
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.2
update_min_a: 0.5 # pi/5 (~ 36°)
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
resample_interval: 1

# Frequencies and latencies
transform_tolerance: 0.1
gui_publish_rate: 10.0

# Map is static
first_map_only: true

# Laser Rangefinder parameters
laser_min_range: -1.0  # use minimum's laser value
laser_max_range: -1.0  # as above
laser_max_beams: 30
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

# odometry related prameters
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.8
odom_alpha4: 0.2
odom_alpha5: 0.1
odom_model_type: diff
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

# 
# amcl_params.yaml ends here
