GlobalPlanner: {
  verbose: false,
  heading_lookahead: 0.5,
  dijkstra/heading_lookahead: 0.75, 
  dijkstra/use_dijkstra: true,
  dijkstra/allow_unknown: false,
  dijkstra/default_tolerance: 0.0,
  dijkstra/old_navfn_behavior: false,
  dijkstra/use_quadratic: true,
  dijkstra/use_grid_path: false,
  dijkstra/visualize_potential: false,
  lattice/heading_lookahead: 0.75, 
  lattice/planner_type: ARAPlanner,
  lattice/environment_type: XYThetaLattice,
  lattice/allocated_time: 10.0,
  lattice/initial_epsilon: 3.0,
  lattice/force_scratch_limit: 500,
  lattice/forward_search: false,
  lattice/lethal_obstacle: 20,
}