# move_base_params.yaml --- 
# 
# Filename: move_base_params.yaml
# Description: Parameters for move_base node 
# Created: Tue Nov 18 00:05:26 2014 (+0100)
# Maintainer: boniardi@cs.uni-freiburg.de
#
# Code:

base_local_planner: "squirrel_navigation/LocalPlanner"
base_global_planner: "squirrel_navigation/GlobalPlanner"
trajectory_planner:
  xy_smoother: 0.75
  yaw_smoother: 0.25
  time_scaler: 1.0
  heading_lookahead: 5
planner_frequency: 1.0
planner_patience: 3.0
recovery_behavior: 
  - {name: rotate_recovery, type: "rotate_recovery/RotateRecovery"}
controller_frequency: 15.0
controller_patience: 5.0
shutdown_costmaps: false

# 
# move_base.yaml ends here